name: ci/cd piplelane

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout the code
              uses: actions/checkout@v2
            - name: setup go
              uses: actions/setup-go@v3
              with:
                go-version: '1.21'
            - name: run test
              run: |
                go test -v ./...

    build-and-push-docker:
        runs-on: ubuntu-latest
        needs: test
        steps:
            - name: checkout the code
              uses: actions/checkout@v2
            - name: create env file
              run: |
                echo "${{secrets.ENV}}" >> .env
            - name: build docker
              run: docker build -t ridhomauludin/donasipohon:1.0.0 .
            - name: docker hub login
              uses: docker/login-action@v1
              with: 
                username: ${{secrets.DOCKER_USER}}
                password: ${{secrets.DOCKER_TOKEN}}
            - name: push image
              run: docker push ridhomauludin/donasipohon:1.0.0
    deploy:
      needs: build-and-push-docker
      runs-on: ubuntu-latest
      env:
        IMAGE_URI: 'ridhomauludin/donasipohon:1.0.0'
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}

      steps:
        - name: Check out the code
          uses: actions/checkout@v2

        - name: Create PEM file from secret
          run: |
            echo "${{ secrets.EC2_PEM }}" > ec2-key.pem
            chmod 600 ec2-key.pem  # Set appropriate permissions


          

